const STATE={data:null,route:'overview',company:null,report:'balance_sheet'};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const REPORT_LABELS={balance_sheet:'Cân đối kế toán',income_statement:'KQKD',cash_flow:'Lưu chuyển tiền tệ',ratio:'Tỷ số'};

function fmt(v,d=2){if(v===null||v===undefined||v===''||Number.isNaN(Number(v)))return 'N/A';return Number(v).toLocaleString('vi-VN',{maximumFractionDigits:d});}
function pct(v,d=1){if(v===null||v===undefined||Number.isNaN(Number(v)))return 'N/A';return `${(Number(v)*100).toFixed(d)}%`;}
function signedPct(v,d=1){if(v===null||v===undefined||Number.isNaN(Number(v)))return 'N/A';const n=Number(v)*100;return `${n>0?'+':''}${n.toFixed(d)}%`;}
function signed(v,d=0){if(v===null||v===undefined||Number.isNaN(Number(v)))return 'N/A';const n=Number(v);return `${n>0?'+':''}${n.toFixed(d)}`;}
function cls(v){return Number(v)>0?'positive':Number(v)<0?'negative':'muted';}
function dateText(v){if(!v)return 'Chưa có';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'});}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function metricByKey(key){return STATE.data?.macro?.metrics?.find(x=>x.key===key)||null;}

function sparkline(values=[]){const nums=values.filter(v=>Number.isFinite(Number(v))).map(Number);if(nums.length<2)return '<span class="muted">—</span>';const w=64,h=20,min=Math.min(...nums),max=Math.max(...nums),span=max-min||1;const pts=nums.map((v,i)=>`${(i/(nums.length-1))*w},${h-2-((v-min)/span)*(h-4)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" aria-hidden="true"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg>`;}

function notice(text,type=''){return `<div class="notice ${type}">${escapeHtml(text)}</div>`;}
function metricCard(label,value,meta='',source=''){return `<article class="metric-card"><div class="metric-label">${escapeHtml(label)}</div><div class="metric-value">${value}</div><div class="metric-meta">${escapeHtml(meta)}</div>${source?`<div class="metric-source">${escapeHtml(source)}</div>`:''}</article>`;}

function navigate(route){STATE.route=route;$$('[data-screen]').forEach(el=>el.classList.toggle('active',el.dataset.screen===route));$$('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===route));window.scrollTo({top:0,behavior:'instant'});}
function wireNavigation(){$$('[data-route]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.route)));$('#refreshBtn')?.addEventListener('click',loadData);}

function renderStatus(){const d=STATE.data||{};const status=d.pipeline_status||'error';const dot=$('#pipelineDot');dot.className=`status-dot ${status==='ok'?'ok':status==='partial'?'partial':'error'}`;$('#pipelineLabel').textContent=status==='ok'?'Pipeline OK':status==='partial'?'Pipeline partial':status==='not_run'?'Chưa chạy':'Pipeline lỗi';$('#generatedAt').textContent=dateText(d.generated_at);$('#overviewFreshness').textContent=dateText(d.generated_at);}

function renderOverview(){const d=STATE.data;const root=$('#overviewNotice');if(d.pipeline_status==='not_run')root.innerHTML=notice('Pipeline chưa tạo snapshot đầu tiên. Dữ liệu hiện tại là placeholder có chủ ý.','warning');else if(d.health?.errors?.length)root.innerHTML=notice(`Có ${d.health.errors.length} lỗi pipeline. Xem tab Dữ liệu.`,'error');else if(d.pipeline_status==='partial')root.innerHTML=notice('Một số layer chưa đủ nguồn. Rootvalue vẫn hiển thị phần đã xác minh và đánh dấu phần còn thiếu.','warning');else root.innerHTML='';
  const idx=d.market?.index||{};const usd=metricByKey('usd_vcb_sell');const gold=metricByKey('gold_sjc_sell');const rows=d.market?.rows||[];const leading=[...rows].sort((a,b)=>(a.rank_current??999)-(b.rank_current??999))[0];
  $('#systemMetrics').innerHTML=[
    metricCard('VNINDEX',fmt(idx.close,2),idx.return_1d==null?'Chưa có biến động phiên':`1D ${signedPct(idx.return_1d)}`,d.market?.source||''),
    metricCard('USD/VND proxy',usd?fmt(usd.value,0):'N/A',usd?.interpretation||'VCB sell; không phải tỷ giá trung tâm SBV',usd?.source||''),
    metricCard('SJC gold',gold?fmt(gold.value,0):'N/A',gold?.interpretation||'Defensive-asset proxy',gold?.source||''),
    metricCard('RS leader',leading?.symbol||'N/A',leading?`Rank #${leading.rank_current} · RS20D ${signedPct(leading.rs_20d_vs_vnindex)}`:'Chưa có market snapshot','V1 watchlist only')
  ].join('');
  const changed=[...rows].filter(r=>r.rank_delta!=null).sort((a,b)=>Math.abs(b.rank_delta)-Math.abs(a.rank_delta)).slice(0,8);$('#changeList').innerHTML=changed.length?changed.map(r=>`<article class="change-item"><div class="change-symbol">${escapeHtml(r.symbol)}</div><div class="change-sector">${escapeHtml(r.sector)}</div><div class="change-reason">RS rank ${r.rank_5d_ago??'—'} → <strong>${r.rank_current??'—'}</strong> · ${escapeHtml(r.state)}</div><div class="change-score ${cls(r.rank_delta)}">${signed(r.rank_delta,0)} bậc</div></article>`).join(''):notice('Chưa đủ dữ liệu để tạo change list.');}

function renderMoney(){const d=STATE.data;const usd=metricByKey('usd_vcb_sell');const rows=d.market?.rows||[];const leader=[...rows].sort((a,b)=>(a.rank_current??999)-(b.rank_current??999))[0];$('#externalValue').textContent='Global inputs: chưa nối V1';$('#fxValue').textContent=usd?.value!=null?`VCB sell ${fmt(usd.value,0)}`:'FX proxy: N/A';const missing=d.macro?.missing_core||[];$('#liquidityValue').textContent=missing.includes('Interbank O/N')?'Core liquidity: chưa nối':'Interbank dataset available';$('#allocationValue').textContent=leader?`RS leader: ${leader.symbol}`:'Market proxy: N/A';const ready=d.macro?.reaction_engine_status==='data_ready';$('#reactionStatus').textContent=ready?'Data ready':'Chưa đủ data';$('#reactionStatus').className=`pill ${ready?'ok':'warning'}`;$('#missingCore').innerHTML=missing.length?missing.map(x=>`<div class="missing-item"><strong>${escapeHtml(x)}</strong><span>missing</span></div>`).join(''):'<div class="missing-item"><strong>Core set</strong><span>available</span></div>';const metrics=d.macro?.metrics||[];$('#macroMetrics').innerHTML=metrics.length?metrics.map(m=>`<div class="stack-item"><div><strong>${escapeHtml(m.label)}</strong><small>${escapeHtml(m.source||'')}</small></div><div>${fmt(m.value,2)} <small>${escapeHtml(m.unit||'')}</small></div></div>`).join(''):'<div class="stack-item"><span>Chưa có proxy tự động</span><small>N/A</small></div>';}

function renderMarket(){const d=STATE.data;const rows=[...(d.market?.rows||[])].sort((a,b)=>(a.rank_current??999)-(b.rank_current??999));$('#marketBody').innerHTML=rows.length?rows.map(r=>`<tr><td><span class="ticker">${escapeHtml(r.symbol)}</span></td><td>${escapeHtml(r.sector)}</td><td>${fmt(r.close,2)}</td><td class="${cls(r.return_1d)}">${signedPct(r.return_1d)}</td><td class="${cls(r.rs_20d_vs_vnindex)}">${signedPct(r.rs_20d_vs_vnindex)}</td><td>#${r.rank_current??'—'}</td><td class="${cls(r.rank_delta)}">${signed(r.rank_delta,0)}</td><td>${r.volume_participation_5d_vs_20d==null?'N/A':`${fmt(r.volume_participation_5d_vs_20d,2)}x`}</td><td>${pct(r.range_position_20d,0)}</td><td><span class="state-badge ${escapeHtml(r.state)}">${escapeHtml(r.state)}</span></td><td>${sparkline(r.sparkline)}</td></tr>`).join(''):`<tr><td colspan="11">Chưa có market snapshot.</td></tr>`;const m=d.market?.methodology||{};$('#marketMethod').innerHTML=Object.entries(m).map(([k,v])=>`<strong>${escapeHtml(k)}</strong>: ${escapeHtml(v)}`).join(' · ');}

function renderCompany(){const companies=STATE.data?.companies?.rows||{};const symbols=Object.keys(companies);const select=$('#companySelect');if(!STATE.company||!companies[STATE.company])STATE.company=symbols[0]||null;select.innerHTML=symbols.length?symbols.map(s=>`<option value="${escapeHtml(s)}" ${s===STATE.company?'selected':''}>${escapeHtml(s)}</option>`).join(''):'<option>Chưa có dữ liệu</option>';select.disabled=!symbols.length;select.onchange=e=>{STATE.company=e.target.value;STATE.report='balance_sheet';renderCompany()};const company=STATE.company?companies[STATE.company]:null;$('#companyNotice').innerHTML=company?notice(`${STATE.company} · ${STATE.data.companies.limitations||company.note||''}`):notice('Chưa có BCTC. Pipeline sẽ giữ nguyên trạng thái N/A thay vì tạo số mẫu.','warning');const tabs=$('#reportTabs');tabs.innerHTML=company?Object.keys(REPORT_LABELS).map(k=>`<button class="report-tab ${STATE.report===k?'active':''}" data-report="${k}">${REPORT_LABELS[k]}</button>`).join(''):'';$$('[data-report]',tabs).forEach(btn=>btn.addEventListener('click',()=>{STATE.report=btn.dataset.report;renderCompany()}));renderFinancialTable(company?.reports?.[STATE.report]);}

function renderFinancialTable(report){const table=$('#financialTable');if(!report||!report.columns?.length){table.innerHTML='<tbody><tr><td>Report unavailable.</td></tr></tbody>';return;}const head=`<thead><tr>${report.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead>`;const body=`<tbody>${(report.rows||[]).map(row=>`<tr>${row.map((v,i)=>`<td>${i===0?escapeHtml(v??''):(typeof v==='number'?fmt(v,2):escapeHtml(v??''))}</td>`).join('')}</tr>`).join('')}</tbody>`;table.innerHTML=head+body;}

function renderData(){const d=STATE.data;const sections=[['Market',d.market],['Macro / liquidity',d.macro],['Fundamental',d.companies]];$('#sourceCards').innerHTML=sections.map(([name,s])=>`<article class="source-card"><span class="eyebrow">${escapeHtml(name)}</span><h3>${escapeHtml((s?.status||'unknown').toUpperCase())}</h3><p>${escapeHtml(Array.isArray(s?.source)?s.source.join(' · '):(s?.source||'No source'))}</p><div class="source-status">As of: ${escapeHtml(dateText(s?.as_of))}</div></article>`).join('');const health=d.health||{};const items=[...(health.errors||[]).map(x=>['error',x]),...(health.warnings||[]).map(x=>['warning',x])];$('#healthList').innerHTML=items.length?items.map(([type,text])=>`<div class="health-item ${type}"><strong>${type.toUpperCase()}</strong><span>${escapeHtml(text)}</span></div>`).join(''):'<div class="health-item"><span>Không có error/warning.</span></div>';const m=d.market?.methodology||{};$('#methodList').innerHTML=Object.entries(m).map(([k,v])=>`<div class="formula-item"><strong>${escapeHtml(k)}</strong><span>${escapeHtml(v)}</span></div>`).join('')||'<div class="formula-item"><span>Chưa có derived metrics.</span></div>';}

function renderAll(){renderStatus();renderOverview();renderMoney();renderMarket();renderCompany();renderData();}

async function loadData(){try{const res=await fetch(`data/rootvalue.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);STATE.data=await res.json();renderAll();}catch(err){STATE.data={pipeline_status:'error',generated_at:null,macro:{metrics:[],missing_core:[]},market:{rows:[],index:{}},companies:{rows:{}},health:{errors:[`Không tải được data/rootvalue.json: ${err.message}`],warnings:[]}};renderAll();}}

wireNavigation();loadData();if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
