const STATE={
  data:null,
  resources:{root:null,market:null,global:null,companyDashboard:null,knowledge:null},
  resourceErrors:[],
  loadId:0,
  loadController:null,
  route:'overview',
  company:null,
  report:'balance_sheet',
  lang:localStorage.getItem('rootvalue-lang')||'vi',
  theme:localStorage.getItem('rootvalue-theme')||'light'
};

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];

const I18N={
  vi:{
    'brand.tag':'DỮ KIỆN TRƯỚC NHẬN ĐỊNH.','theme.dark':'Tối','theme.light':'Sáng','action.refresh':'Tải lại dữ liệu','action.language':'Đổi ngôn ngữ','action.theme':'Đổi giao diện',
    'nav.overview':'Tổng quan','nav.money':'Dòng tiền hệ thống','nav.market':'Dòng tiền thị trường','nav.company':'Doanh nghiệp','nav.data':'Dữ liệu','nav.knowledge':'Kiến thức',
    'nav.overview.short':'Tổng quan','nav.money.short':'Hệ thống','nav.market.short':'Thị trường','nav.company.short':'Cổ phiếu','nav.data.short':'Dữ liệu','nav.knowledge.short':'Kiến thức',
    'pipeline.loading':'Đang tải','pipeline.ok':'Dữ liệu ổn','pipeline.partial':'Dữ liệu một phần','pipeline.notRun':'Chưa chạy','pipeline.error':'Lỗi dữ liệu',
    'overview.title':'Điều gì đã thay đổi?','overview.lead':'Từ thanh khoản hệ thống đến doanh nghiệp. Chỉ hiển thị dữ kiện có nguồn và độ mới rõ ràng.','data.label':'DỮ LIỆU',
    'attention.kicker':'ĐÁNG CHÚ Ý','attention.title':'Biến động cần xem','attention.note':'xếp hạng trong danh sách theo dõi V1',
    'money.kicker':'TỪ TRÊN XUỐNG','money.title':'Dòng tiền hệ thống','money.lead':'Áp lực bên ngoài → tỷ giá và phản ứng của NHNN → thanh khoản VND → phân bổ tài sản.',
    'flow.external.title':'Bên ngoài','flow.external.desc':'DXY / Fed / thương mại / FDI / hàng hóa / biến động chính trị',
    'flow.sbv.title':'Tỷ giá + NHNN','flow.sbv.desc':'Áp lực USD/VND, can thiệp và lựa chọn chính sách',
    'flow.liquidity.title':'Thanh khoản VND','flow.liquidity.desc':'Liên ngân hàng / OMO / tín phiếu / Kho bạc / chênh lệch huy động-tín dụng',
    'flow.allocation.title':'Phân bổ','flow.allocation.desc':'Tiền gửi / trái phiếu / cổ phiếu / bất động sản / vàng',
    'reaction.kicker':'MÔ HÌNH PHẢN ỨNG NHNN','reaction.title':'V0 — mới có khung','reaction.missing':'Chưa đủ dữ liệu','reaction.ready':'Đã đủ dữ liệu nền',
    'reaction.desc':'Chưa gán xác suất nới lỏng / trung lập / phòng thủ cho đến khi OMO, lãi suất liên ngân hàng và các biến thanh khoản cốt lõi được nối và kiểm định.',
    'proxy.kicker':'DỮ LIỆU ĐÃ CÓ','proxy.title':'Các biến đại diện',
    'market.kicker':'SO SÁNH CHÉO','market.title':'Dòng tiền thị trường','market.lead':'Dùng sức mạnh tương đối và mức tham gia để nhận diện sự thay đổi vị thế. Không coi giá và khối lượng là bằng chứng tiền chuyển trực tiếp từ mã A sang mã B.',
    'table.symbol':'Mã','table.sector':'Ngành','table.price':'Giá','table.rs20':'Sức mạnh 20P','table.rank':'Xếp hạng','table.rankChange':'Δ hạng','table.participation':'Mức tham gia','table.range20':'Vị trí 20P','table.state':'Trạng thái',
    'company.kicker':'TỪ DƯỚI LÊN','company.title':'Doanh nghiệp','company.lead':'Báo cáo tài chính theo chuỗi thời gian, ưu tiên 5–10 năm. Nếu nguồn chỉ trả về ít kỳ hơn, hệ thống ghi rõ độ phủ thay vì lấp bằng số giả.','company.symbol':'Mã',
    'provenance.kicker':'NGUỒN GỐC DỮ LIỆU','data.title':'Dữ liệu & kiểm soát','data.lead':'Nguồn, độ mới, lỗi và giới hạn nằm ngay trong mô hình dữ liệu.','pipeline.kicker':'LUỒNG CẬP NHẬT','pipeline.health':'Lỗi / cảnh báo','formula.kicker':'CÔNG THỨC','formula.title':'Chỉ số thị trường suy ra',
    'report.balance_sheet':'Cân đối kế toán','report.income_statement':'Kết quả kinh doanh','report.cash_flow':'Lưu chuyển tiền tệ','report.ratio':'Tỷ số tài chính',
    'state.Leading':'Dẫn dắt','state.Improving':'Cải thiện','state.Neutral':'Trung tính','state.Weakening':'Suy yếu',
    'notice.notRun':'Luồng tự động chưa tạo được bản dữ liệu đầu tiên. Đây là lỗi hạ tầng dữ liệu, không phải trạng thái thị trường.','notice.errors':'Có lỗi trong luồng cập nhật. Xem mục Dữ liệu.','notice.partial':'Một số lớp dữ liệu chưa đủ nguồn. Phần đã xác minh vẫn được hiển thị và phần còn thiếu được đánh dấu rõ.','notice.noChanges':'Chưa đủ dữ liệu để tạo danh sách biến động.',
    'metric.vnindex':'VNINDEX','metric.fx':'USD/VND đại diện','metric.gold':'Vàng SJC','metric.leader':'Dẫn đầu sức mạnh tương đối','metric.noMove':'Chưa có biến động phiên','metric.fxDesc':'Giá bán USD tại VCB; không phải tỷ giá trung tâm NHNN','metric.goldDesc':'Biến đại diện cho tài sản phòng thủ trong nước','metric.watchlist':'Chỉ trong danh sách theo dõi V1',
    'money.externalMissing':'Dữ liệu toàn cầu: chưa nối ở V1','money.fxMissing':'Tỷ giá đại diện: N/A','money.liquidityMissing':'Thanh khoản cốt lõi: chưa nối','money.liquidityReady':'Đã có dữ liệu liên ngân hàng','money.allocationMissing':'Thị trường: N/A','money.rsLeader':'Mã dẫn đầu sức mạnh tương đối',
    'missing.status':'thiếu','missing.available':'đã có','missing.coreSet':'Bộ dữ liệu cốt lõi','proxy.none':'Chưa có dữ liệu đại diện tự động',
    'company.noData':'Chưa có báo cáo tài chính. Hệ thống giữ N/A thay vì tạo số mẫu.','company.coverage':'Độ phủ lịch sử','company.coverageCommon':'Đủ cả 3 BCTC','company.target':'Mục tiêu','company.years':'năm','company.periods':'kỳ năm','company.needKey':'Chưa đạt mục tiêu lịch sử chung; xem số kỳ từng báo cáo và tình trạng nguồn.','company.limit8':'V1 đặt mục tiêu 8 năm; muốn đủ 10 năm cần nguồn có lịch sử dài hơn hoặc gói dữ liệu mở rộng.','company.item':'Chỉ tiêu','company.unit':'Đơn vị','company.reportUnavailable':'Báo cáo chưa khả dụng.',
    'data.market':'Thị trường','data.macro':'Vĩ mô / thanh khoản','data.fundamental':'Báo cáo tài chính','data.global':'Toàn cầu','data.source':'Nguồn','data.asOf':'Ngày quan sát nguồn','data.fetched':'Rootvalue cập nhật','data.noSource':'Chưa có nguồn','data.noIssues':'Không có lỗi hoặc cảnh báo.','data.error':'Lỗi','data.warning':'Cảnh báo','data.seeLogs':'Xem nhật ký GitHub Actions để biết chi tiết kỹ thuật.',
    'method.rs_20d':'Lợi suất 20 phiên của cổ phiếu trừ lợi suất 20 phiên của VNINDEX.','method.rank_current':'Xếp hạng chéo trong danh sách theo dõi V1.','method.rank_delta':'Xếp hạng 5 phiên trước trừ xếp hạng hiện tại; số dương nghĩa là cải thiện.','method.participation':'Khối lượng trung bình 5 phiên chia khối lượng trung bình 20 phiên; đây là biến đại diện cho mức tham gia, không chứng minh tiền chuyển trực tiếp.','method.range_position':'(Giá đóng cửa - đáy 20 phiên) / (đỉnh 20 phiên - đáy 20 phiên).',
    'missing.SBV central exchange rate':'Tỷ giá trung tâm NHNN','missing.Interbank O/N':'Lãi suất liên ngân hàng qua đêm','missing.OMO outstanding/rate':'Khối lượng và lãi suất OMO','missing.SBV bills outstanding':'Tín phiếu NHNN đang lưu hành','missing.Treasury liquidity proxy':'Biến đại diện thanh khoản Kho bạc','missing.Credit growth':'Tăng trưởng tín dụng','missing.Deposit growth':'Tăng trưởng huy động'
  },
  en:{
    'brand.tag':'EVIDENCE BEFORE OPINION.','theme.dark':'Dark','theme.light':'Light','action.refresh':'Reload data','action.language':'Switch language','action.theme':'Change theme',
    'nav.overview':'Overview','nav.money':'System Money Flow','nav.market':'Market Flow','nav.company':'Companies','nav.data':'Data','nav.knowledge':'Knowledge',
    'nav.overview.short':'Overview','nav.money.short':'System','nav.market.short':'Market','nav.company.short':'Stocks','nav.data.short':'Data','nav.knowledge.short':'Knowledge',
    'pipeline.loading':'Loading','pipeline.ok':'Data OK','pipeline.partial':'Partial data','pipeline.notRun':'Not run','pipeline.error':'Data error',
    'overview.title':'What changed?','overview.lead':'From system liquidity to individual companies. Only sourced and time-stamped evidence is shown.','data.label':'DATA',
    'attention.kicker':'ATTENTION','attention.title':'Changes worth reviewing','attention.note':'ranked inside the V1 watchlist',
    'money.kicker':'TOP-DOWN','money.title':'System Money Flow','money.lead':'External pressure → FX and SBV reaction → VND liquidity → asset allocation.',
    'flow.external.title':'External','flow.external.desc':'DXY / Fed / trade / FDI / commodities / political shocks',
    'flow.sbv.title':'FX + SBV','flow.sbv.desc':'USD/VND pressure, intervention and policy choice',
    'flow.liquidity.title':'VND Liquidity','flow.liquidity.desc':'Interbank / OMO / bills / Treasury / deposit-credit gap',
    'flow.allocation.title':'Allocation','flow.allocation.desc':'Deposits / bonds / equities / property / gold',
    'reaction.kicker':'SBV REACTION MODEL','reaction.title':'V0 — framework only','reaction.missing':'Insufficient data','reaction.ready':'Core data ready',
    'reaction.desc':'No easing / neutral / defend probabilities are assigned until OMO, interbank rates and the core liquidity variables are wired and validated.',
    'proxy.kicker':'AVAILABLE DATA','proxy.title':'Current proxies',
    'market.kicker':'CROSS-SECTIONAL','market.title':'Market Flow','market.lead':'Relative strength and participation are used to detect leadership changes. Price and volume are not treated as proof that cash moved directly from stock A to stock B.',
    'table.symbol':'Symbol','table.sector':'Sector','table.price':'Price','table.rs20':'20D Strength','table.rank':'Rank','table.rankChange':'Δ Rank','table.participation':'Participation','table.range20':'20D Position','table.state':'State',
    'company.kicker':'BOTTOM-UP','company.title':'Companies','company.lead':'Financial statements are shown as time series with a 5–10 year target. If the source returns fewer periods, coverage is disclosed rather than fabricated.','company.symbol':'Symbol',
    'provenance.kicker':'PROVENANCE','data.title':'Data & Controls','data.lead':'Source, freshness, errors and limitations are part of the data model.','pipeline.kicker':'PIPELINE','pipeline.health':'Errors / warnings','formula.kicker':'FORMULAS','formula.title':'Derived market metrics',
    'report.balance_sheet':'Balance Sheet','report.income_statement':'Income Statement','report.cash_flow':'Cash Flow','report.ratio':'Financial Ratios',
    'state.Leading':'Leading','state.Improving':'Improving','state.Neutral':'Neutral','state.Weakening':'Weakening',
    'notice.notRun':'The automated pipeline has not produced its first data snapshot. This is a data-infrastructure issue, not a market state.','notice.errors':'The update pipeline has errors. See Data.','notice.partial':'Some data layers are incomplete. Verified data remains visible and missing layers are explicitly marked.','notice.noChanges':'Insufficient data to build a change list.',
    'metric.vnindex':'VNINDEX','metric.fx':'USD/VND proxy','metric.gold':'SJC Gold','metric.leader':'Relative-strength leader','metric.noMove':'No session change available','metric.fxDesc':'VCB USD selling rate; not the SBV central rate','metric.goldDesc':'Domestic defensive-asset proxy','metric.watchlist':'V1 watchlist only',
    'money.externalMissing':'Global inputs: not wired in V1','money.fxMissing':'FX proxy: N/A','money.liquidityMissing':'Core liquidity: not wired','money.liquidityReady':'Interbank dataset available','money.allocationMissing':'Market proxy: N/A','money.rsLeader':'Relative-strength leader',
    'missing.status':'missing','missing.available':'available','missing.coreSet':'Core dataset','proxy.none':'No automated proxy available',
    'company.noData':'No financial statements available. The system keeps N/A rather than generating sample numbers.','company.coverage':'History coverage','company.coverageCommon':'Common core statements','company.target':'Target','company.years':'years','company.periods':'annual periods','company.needKey':'Common history is below target; review each report count and source status.','company.limit8':'V1 targets 8 years; a full 10-year history requires a longer-history source or expanded data access.','company.item':'Item','company.unit':'Unit','company.reportUnavailable':'Report unavailable.',
    'data.market':'Market','data.macro':'Macro / liquidity','data.fundamental':'Financial statements','data.global':'Global','data.source':'Source','data.asOf':'Source observation','data.fetched':'Rootvalue updated','data.noSource':'No source','data.noIssues':'No errors or warnings.','data.error':'Error','data.warning':'Warning','data.seeLogs':'See GitHub Actions logs for technical details.',
    'method.rs_20d':'Stock 20-session return minus VNINDEX 20-session return.','method.rank_current':'Cross-sectional rank inside the V1 watchlist.','method.rank_delta':'Rank five sessions ago minus current rank; positive means improving.','method.participation':'Five-session average volume divided by 20-session average volume; a participation proxy, not proof of direct cash transfer.','method.range_position':'(Close - 20D low) / (20D high - 20D low).',
    'missing.SBV central exchange rate':'SBV central exchange rate','missing.Interbank O/N':'Interbank overnight rate','missing.OMO outstanding/rate':'OMO outstanding / rate','missing.SBV bills outstanding':'SBV bills outstanding','missing.Treasury liquidity proxy':'Treasury liquidity proxy','missing.Credit growth':'Credit growth','missing.Deposit growth':'Deposit growth'
  }
};

const REPORTS=['balance_sheet','income_statement','cash_flow','ratio'];
const METHOD_KEYS=['rs_20d','rank_current','rank_delta','participation','range_position'];
const SECTORS={
  'Banking':{vi:'Ngân hàng',en:'Banking'},'Steel':{vi:'Thép',en:'Steel'},'Technology':{vi:'Công nghệ',en:'Technology'},'Retail':{vi:'Bán lẻ',en:'Retail'},'Consumer':{vi:'Tiêu dùng',en:'Consumer'},'Ports & Logistics':{vi:'Cảng & logistics',en:'Ports & Logistics'},'Energy Transport':{vi:'Vận tải năng lượng',en:'Energy Transport'},'Utilities & Infrastructure':{vi:'Tiện ích & hạ tầng',en:'Utilities & Infrastructure'}
};

function t(key){return I18N[STATE.lang]?.[key]??I18N.vi[key]??key;}
function locale(){return STATE.lang==='vi'?'vi-VN':'en-US';}
function sectorLabel(s){return SECTORS[s]?.[STATE.lang]||s||'—';}
function sourceLabel(source){const raw=Array.isArray(source)?source.join(' · '):String(source||'');if(!raw)return t('data.noSource');const names=[];if(/Vnstock/i.test(raw))names.push('Vnstock');if(/Vietcombank/i.test(raw))names.push('Vietcombank');if(/SJC/i.test(raw))names.push('SJC');if(/MAS/i.test(raw))names.push('MAS');if(/VCI|Vietcap/i.test(raw))names.push('Vietcap');return [...new Set(names)].join(' / ')||raw;}
function toFinite(v){if(v===null||v===undefined||(typeof v==='string'&&!v.trim()))return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function fmt(v,d=2){const n=toFinite(v);return n===null?'N/A':n.toLocaleString(locale(),{maximumFractionDigits:d});}
function pct(v,d=1){const n=toFinite(v);return n===null?'N/A':`${(n*100).toFixed(d)}%`;}
function signedPct(v,d=1){const raw=toFinite(v);if(raw===null)return 'N/A';const n=raw*100;return `${n>0?'+':''}${n.toFixed(d)}%`;}
function signed(v,d=0){const n=toFinite(v);return n===null?'N/A':`${n>0?'+':''}${n.toFixed(d)}`;}
function cls(v){const n=toFinite(v);return n===null?'muted':n>0?'positive':n<0?'negative':'muted';}
function rankValue(v){const n=toFinite(v);return n===null?999:n;}
function rankText(v){const n=toFinite(v);return n===null?'—':fmt(n,0);}
function dateText(v){if(!v)return '—';const raw=String(v);if(/^\d{4}$/.test(raw))return raw;if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const d=new Date(`${raw}T00:00:00`);return d.toLocaleDateString(locale(),{dateStyle:'short'});}const d=new Date(raw);return Number.isNaN(d.getTime())?raw:d.toLocaleString(locale(),{dateStyle:'short',timeStyle:'short'});}
function dateSortValue(v){const raw=String(v||'');if(/^\d{4}$/.test(raw))return Date.UTC(Number(raw),11,31);const parsed=new Date(raw).getTime();return Number.isFinite(parsed)?parsed:-Infinity;}
function latestDateValue(values=[]){return values.filter(Boolean).map(raw=>({raw,time:dateSortValue(raw)})).filter(x=>Number.isFinite(x.time)).sort((a,b)=>b.time-a.time)[0]?.raw||null;}
function resourceObservationTime(key){const r=STATE.resources||{},d=STATE.data||{};if(key==='market')return r.market?.source_observation_date||r.market?.as_of||d.market?.source_observation_date||d.market?.as_of;if(key==='global')return latestDateValue(Object.values(r.global?.series||{}).map(x=>x?.source_observation_date||x?.as_of))||r.global?.source_observation_date||r.global?.as_of;if(key==='company')return d.companies?.source_observation_date||d.companies?.as_of||latestDateValue(Object.values(r.companyDashboard?.companies||{}).map(x=>x?.source_observation_date||x?.source_as_of));if(key==='macro')return d.macro?.sbv_current?.source_observation_date||d.macro?.source_observation_date||d.macro?.as_of;return null;}
function resourceFetchedTime(key){const r=STATE.resources||{},d=STATE.data||{};if(key==='market')return r.market?.fetched_at||r.market?.generated_at||d.market?.fetched_at||d.market?.generated_at;if(key==='global')return r.global?.fetched_at||r.global?.generated_at;if(key==='company')return d.companies?.fetched_at||latestDateValue(Object.values(r.companyDashboard?.companies||{}).map(x=>x?.fetched_at||x?.source_generated_at))||r.companyDashboard?.generated_at;if(key==='macro')return d.macro?.fetched_at||r.root?.generated_at||d.generated_at;return r.root?.fetched_at||r.root?.generated_at||d.generated_at;}
function componentFreshnessText(){const labels=STATE.lang==='vi'?{market:'TT',macro:'Vĩ mô',company:'BCTC'}:{market:'MKT',macro:'Macro',company:'Financials'};return ['market','macro','company'].map(k=>`${labels[k]} ${dateText(resourceObservationTime(k))}`).join(' · ');}
function latestResourceTime(){return latestDateValue(['root','market','global','company','macro'].map(resourceFetchedTime));}
function freshnessBreakdown(){const labels=STATE.lang==='vi'?{market:'Thị trường',macro:'Vĩ mô',company:'BCTC',global:'Toàn cầu'}:{market:'Market',macro:'Macro',company:'Financials',global:'Global'};return ['market','macro','company','global'].map(k=>`${labels[k]}: ${t('data.asOf')} ${dateText(resourceObservationTime(k))}; ${t('data.fetched')} ${dateText(resourceFetchedTime(k))}`).join(' · ');}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function metricByKey(key){return STATE.data?.macro?.metrics?.find(x=>x.key===key)||null;}
function stateLabel(state){return t(`state.${state}`);}
function missingLabel(x){return t(`missing.${x}`);}

function applyTheme(){document.documentElement.dataset.theme=STATE.theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',STATE.theme==='dark'?'#171717':'#F7F7F5');$$('.theme-icon').forEach(x=>x.textContent=STATE.theme==='dark'?'☀':'☾');$$('.theme-label').forEach(x=>x.textContent=STATE.theme==='dark'?t('theme.light'):t('theme.dark'));$$('.theme-toggle').forEach(x=>x.setAttribute('aria-pressed',String(STATE.theme==='dark')));}
function syncRouteA11y(){$$('[data-screen]').forEach(el=>el.setAttribute('aria-hidden',String(el.dataset.screen!==STATE.route)));$$('[data-route]').forEach(el=>{if(el.dataset.route===STATE.route)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});}
function translateStatic(){document.documentElement.lang=STATE.lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-title]').forEach(el=>{const label=t(el.dataset.i18nTitle);el.title=label;el.setAttribute('aria-label',label);});$$('[data-i18n-aria-label]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAriaLabel)));$$('[data-state-label]').forEach(el=>el.textContent=stateLabel(el.dataset.stateLabel));applyTheme();syncRouteA11y();}
function switchLanguage(){STATE.lang=STATE.lang==='vi'?'en':'vi';localStorage.setItem('rootvalue-lang',STATE.lang);translateStatic();if(STATE.data)renderAll();}
function switchTheme(){STATE.theme=STATE.theme==='light'?'dark':'light';localStorage.setItem('rootvalue-theme',STATE.theme);applyTheme();}

/* Fritsch–Carlson monotone cubic: smooth without inventing extrema between observations. */
function monotonePath(points=[]){
  if(!points.length)return'';
  if(points.length===1)return `M ${points[0].x} ${points[0].y}`;
  if(points.length===2)return `M ${points[0].x} ${points[0].y} L ${points[1].x} ${points[1].y}`;
  const slopes=points.slice(0,-1).map((p,i)=>(points[i+1].y-p.y)/(points[i+1].x-p.x));
  const tangents=new Array(points.length);tangents[0]=slopes[0];tangents[tangents.length-1]=slopes.at(-1);
  for(let i=1;i<points.length-1;i++)tangents[i]=slopes[i-1]*slopes[i]<=0?0:(slopes[i-1]+slopes[i])/2;
  slopes.forEach((s,i)=>{if(s===0){tangents[i]=0;tangents[i+1]=0;return;}const a=tangents[i]/s,b=tangents[i+1]/s,q=a*a+b*b;if(q>9){const scale=3/Math.sqrt(q);tangents[i]=scale*a*s;tangents[i+1]=scale*b*s;}});
  let d=`M ${points[0].x} ${points[0].y}`;
  for(let i=0;i<points.length-1;i++){const p=points[i],next=points[i+1],dx=(next.x-p.x)/3;d+=` C ${p.x+dx} ${p.y+tangents[i]*dx}, ${next.x-dx} ${next.y-tangents[i+1]*dx}, ${next.x} ${next.y}`;}
  return d;
}
function sparkline(values=[]){
  const raw=values.map(toFinite),finite=raw.filter(v=>v!==null);if(finite.length<2)return '<span class="muted">—</span>';
  const w=84,h=26,pad=3,min=Math.min(...finite),max=Math.max(...finite),span=max-min||1,x=i=>raw.length===1?w/2:(i/(raw.length-1))*w,y=v=>h-pad-((v-min)/span)*(h-pad*2);
  const segments=[];let segment=[];raw.forEach((v,i)=>{if(v===null){if(segment.length)segments.push(segment);segment=[];}else segment.push({x:x(i),y:y(v)});});if(segment.length)segments.push(segment);
  const paths=segments.filter(s=>s.length>1).map(s=>`<path class="spark-path" d="${monotonePath(s)}"/>`).join('');
  const lastIndex=raw.findLastIndex(v=>v!==null),last=raw[lastIndex],summary=STATE.lang==='vi'?`${finite.length} quan sát; từ ${fmt(finite[0],2)} đến ${fmt(last,2)}; thấp nhất ${fmt(min,2)}, cao nhất ${fmt(max,2)}.`:`${finite.length} observations; from ${fmt(finite[0],2)} to ${fmt(last,2)}; low ${fmt(min,2)}, high ${fmt(max,2)}.`;
  return `<svg class="spark" viewBox="0 0 ${w} ${h}" role="img" aria-label="${escapeHtml(summary)}"><title>${escapeHtml(summary)}</title>${paths}<circle class="spark-end" cx="${x(lastIndex)}" cy="${y(last)}" r="2.35"/></svg>`;
}
function notice(text,type=''){return `<div class="notice ${type}">${escapeHtml(text)}</div>`;}
function metricCard(label,value,meta='',source=''){return `<article class="metric-card"><div class="metric-label">${escapeHtml(label)}</div><div class="metric-value">${value}</div><div class="metric-meta">${escapeHtml(meta)}</div>${source?`<div class="metric-source">${escapeHtml(sourceLabel(source))}</div>`:''}</article>`;}

function navigate(route){STATE.route=route;$$('[data-screen]').forEach(el=>el.classList.toggle('active',el.dataset.screen===route));$$('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===route));syncRouteA11y();window.scrollTo({top:0,behavior:'instant'});}
function wireControls(){$$('[data-route]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.route)));$('#refreshBtn')?.addEventListener('click',loadData);$$('.lang-toggle').forEach(btn=>btn.addEventListener('click',switchLanguage));$$('.theme-toggle').forEach(btn=>btn.addEventListener('click',switchTheme));}

function renderStatus(){const d=STATE.data||{};const status=d.pipeline_status||'error';const dot=$('#pipelineDot');dot.className=`status-dot ${status==='ok'?'ok':status==='partial'?'partial':'error'}`;$('#pipelineLabel').textContent=status==='ok'?t('pipeline.ok'):status==='partial'?t('pipeline.partial'):status==='not_run'?t('pipeline.notRun'):t('pipeline.error');const latest=latestResourceTime();const breakdown=freshnessBreakdown();const generated=$('#generatedAt');generated.textContent=dateText(latest);generated.title=breakdown;const overview=$('#overviewFreshness');overview.textContent=componentFreshnessText();overview.title=breakdown;}

function renderOverview(){const d=STATE.data;const root=$('#overviewNotice');if(d.pipeline_status==='not_run')root.innerHTML=notice(t('notice.notRun'),'warning');else if(d.health?.errors?.length)root.innerHTML=notice(`${t('notice.errors')} (${d.health.errors.length})`,'error');else if(d.pipeline_status==='partial')root.innerHTML=notice(t('notice.partial'),'warning');else root.innerHTML='';
  const idx=d.market?.index||{};const usd=metricByKey('usd_vcb_sell');const gold=metricByKey('gold_sjc_sell');const rows=d.market?.rows||[];const leading=[...rows].filter(r=>toFinite(r.rank_current)!==null).sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current))[0];
  $('#systemMetrics').innerHTML=[
    metricCard(t('metric.vnindex'),fmt(idx.close,2),toFinite(idx.return_1d)===null?t('metric.noMove'):`1D ${signedPct(idx.return_1d)}`,d.market?.source||''),
    metricCard(t('metric.fx'),usd?fmt(usd.value,0):'N/A',t('metric.fxDesc'),usd?.source||''),
    metricCard(t('metric.gold'),gold?fmt(gold.value,0):'N/A',t('metric.goldDesc'),gold?.source||''),
    metricCard(t('metric.leader'),leading?.symbol||'N/A',leading?`#${leading.rank_current} · ${t('table.rs20')} ${signedPct(leading.rs_20d_vs_vnindex)}`:'N/A',t('metric.watchlist'))
  ].join('');
  const changed=[...rows].filter(r=>toFinite(r.rank_delta)!==null).sort((a,b)=>Math.abs(toFinite(b.rank_delta))-Math.abs(toFinite(a.rank_delta))).slice(0,8);$('#changeList').innerHTML=changed.length?changed.map(r=>`<article class="change-item"><div class="change-symbol">${escapeHtml(r.symbol)}</div><div class="change-sector">${escapeHtml(sectorLabel(r.sector))}</div><div class="change-reason">#${rankText(r.rank_5d_ago)} → <strong>#${rankText(r.rank_current)}</strong> · ${escapeHtml(stateLabel(r.state))}</div><div class="change-score ${cls(r.rank_delta)}">${signed(r.rank_delta,0)}</div></article>`).join(''):notice(t('notice.noChanges'));}

function renderMoney(){const d=STATE.data;const usd=metricByKey('usd_vcb_sell');const rows=d.market?.rows||[];const leader=[...rows].filter(r=>toFinite(r.rank_current)!==null).sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current))[0];$('#externalValue').textContent=t('money.externalMissing');$('#fxValue').textContent=toFinite(usd?.value)!==null?`${fmt(usd.value,0)} VND/USD`:t('money.fxMissing');const missing=d.macro?.missing_core||[];$('#liquidityValue').textContent=missing.includes('Interbank O/N')?t('money.liquidityMissing'):t('money.liquidityReady');$('#allocationValue').textContent=leader?`${t('money.rsLeader')}: ${leader.symbol}`:t('money.allocationMissing');const ready=d.macro?.reaction_engine_status==='data_ready';$('#reactionStatus').textContent=ready?t('reaction.ready'):t('reaction.missing');$('#reactionStatus').className=`pill ${ready?'ok':'warning'}`;$('#missingCore').innerHTML=missing.length?missing.map(x=>`<div class="missing-item"><strong>${escapeHtml(missingLabel(x))}</strong><span>${t('missing.status')}</span></div>`).join(''):`<div class="missing-item"><strong>${t('missing.coreSet')}</strong><span>${t('missing.available')}</span></div>`;const metrics=d.macro?.metrics||[];$('#macroMetrics').innerHTML=metrics.length?metrics.map(m=>`<div class="stack-item"><div><strong>${escapeHtml(m.label)}</strong><small>${escapeHtml(sourceLabel(m.source||''))}</small></div><div>${fmt(m.value,2)} <small>${escapeHtml(m.unit||'')}</small></div></div>`).join(''):`<div class="stack-item"><span>${t('proxy.none')}</span><small>N/A</small></div>`;}

function renderMarket(){const d=STATE.data;const rows=[...(d.market?.rows||[])].sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current));$('#marketBody').innerHTML=rows.length?rows.map(r=>{const participation=toFinite(r.volume_participation_5d_vs_20d);return `<tr><td><span class="ticker">${escapeHtml(r.symbol)}</span></td><td>${escapeHtml(sectorLabel(r.sector))}</td><td>${fmt(r.close,2)}</td><td class="${cls(r.return_1d)}">${signedPct(r.return_1d)}</td><td class="${cls(r.rs_20d_vs_vnindex)}">${signedPct(r.rs_20d_vs_vnindex)}</td><td>#${rankText(r.rank_current)}</td><td class="${cls(r.rank_delta)}">${signed(r.rank_delta,0)}</td><td>${participation===null?'N/A':`${fmt(participation,2)}x`}</td><td>${pct(r.range_position_20d,0)}</td><td><span class="state-badge ${escapeHtml(r.state)}">${escapeHtml(stateLabel(r.state))}</span></td><td>${sparkline(r.sparkline)}</td></tr>`}).join(''):`<tr><td colspan="11">N/A</td></tr>`;$('#marketMethod').innerHTML=METHOD_KEYS.map(k=>`<strong>${escapeHtml(k)}</strong>: ${escapeHtml(t(`method.${k}`))}`).join(' · ');}

const REPORT_META_COLUMNS=new Set(['item','item_vi','item_en','item_id','id','code','name','item_name','item english','english item','unit','đơn vị','ticker','symbol','index']);
const CORE_REPORTS=['balance_sheet','income_statement','cash_flow'];
function reportPeriodIndexes(columns=[]){const candidates=columns.map((c,i)=>[String(c),i]).filter(([c])=>!REPORT_META_COLUMNS.has(c.trim().toLowerCase()));const dated=candidates.filter(([c])=>/(?:^|\D)(?:19|20)\d{2}(?:\D|$)/.test(c));return (dated.length?dated:candidates).map(([,i])=>i);}
function inferPeriodCount(report){return reportPeriodIndexes(report?.columns||[]).length;}
function reportAvailable(report){return !!(report?.columns?.length&&(report.rows||[]).length);}
function ensureAvailableReport(company){if(!company?.reports)return;if(!reportAvailable(company.reports[STATE.report]))STATE.report=REPORTS.find(k=>reportAvailable(company.reports[k]))||STATE.report;}
function reportAnnualYears(report){return new Set(reportPeriodIndexes(report?.columns||[]).map(i=>String(report.columns[i]).match(/(?:19|20)\d{2}/)?.[0]).filter(Boolean));}
function coverageCount(value){if(Array.isArray(value))return new Set(value.map(String)).size;const n=toFinite(value);return n===null?0:Math.max(0,Math.trunc(n));}
function companyCoverage(company){const coverage=company?.coverage||company?.history||{};const reports=company?.reports||{};const declared=coverage.annual_years_by_report||{};const counts={};CORE_REPORTS.forEach(k=>{counts[k]=Object.prototype.hasOwnProperty.call(declared,k)?coverageCount(declared[k]):reportAnnualYears(reports[k]).size;});const hasReports=CORE_REPORTS.some(k=>reports[k]);const declaredPeriods=toFinite(coverage.annual_periods);let common=declaredPeriods===null?null:Math.max(0,Math.trunc(declaredPeriods));if(!Object.keys(declared).length&&hasReports){const sets=CORE_REPORTS.map(k=>reportAnnualYears(reports[k]));common=sets[0]?[...sets[0]].filter(y=>sets.slice(1).every(s=>s.has(y))).length:0;}if(common===null)common=0;const target=coverage.minimum_annual_periods??coverage.target_years??8;return {common,target:coverageCount(target)||8,counts};}
function coverageDetailText(counts){const labels=STATE.lang==='vi'?{balance_sheet:'CĐKT',income_statement:'KQKD',cash_flow:'LCTT'}:{balance_sheet:'BS',income_statement:'IS',cash_flow:'CF'};return CORE_REPORTS.map(k=>`${labels[k]} ${counts[k]??0}`).join(' · ');}
function renderHistoryCoverage(company){const root=$('#historyCoverage');if(!company){root.innerHTML='';return;}const coverage=companyCoverage(company);const warn=coverage.common<coverage.target;root.innerHTML=`<span class="history-chip ${warn?'warning':''}">${t('company.coverageCommon')}: <strong>${coverage.common}/${coverage.target}</strong></span><span class="history-chip">${escapeHtml(coverageDetailText(coverage.counts))}</span>${warn?`<span class="history-chip warning">${escapeHtml(t('company.needKey'))}</span>`:''}${coverage.target<10?`<span class="history-chip">${escapeHtml(t('company.limit8'))}</span>`:''}`;}

function renderCompany(){const companies=STATE.data?.companies?.rows||{};const symbols=Object.keys(companies);const select=$('#companySelect');if(!STATE.company||!companies[STATE.company])STATE.company=symbols[0]||null;select.innerHTML=symbols.length?symbols.map(s=>`<option value="${escapeHtml(s)}" ${s===STATE.company?'selected':''}>${escapeHtml(s)}</option>`).join(''):`<option>N/A</option>`;select.disabled=!symbols.length;select.onchange=e=>{STATE.company=e.target.value;ensureAvailableReport(companies[STATE.company]);renderCompany()};const company=STATE.company?companies[STATE.company]:null;ensureAvailableReport(company);const coverage=companyCoverage(company);$('#companyNotice').innerHTML=company?notice(`${STATE.company} · ${t('company.coverageCommon')}: ${coverage.common}/${coverage.target} · ${coverageDetailText(coverage.counts)}`):notice(t('company.noData'),'warning');renderHistoryCoverage(company);const tabs=$('#reportTabs');tabs.setAttribute('role','tablist');tabs.innerHTML=company?REPORTS.map(k=>`<button type="button" role="tab" aria-selected="${STATE.report===k}" class="report-tab ${STATE.report===k?'active':''}" data-report="${k}">${t(`report.${k}`)}</button>`).join(''):'';$$('[data-report]',tabs).forEach(btn=>btn.addEventListener('click',()=>{STATE.report=btn.dataset.report;renderCompany()}));renderFinancialTable(company?.reports?.[STATE.report]);}

function renderFinancialTable(report){const table=$('#financialTable');if(!reportAvailable(report)){table.innerHTML=`<tbody><tr><td>${escapeHtml(t('company.reportUnavailable'))}</td></tr></tbody>`;return;}const cols=report.columns.map(String);const lc=cols.map(c=>c.trim().toLowerCase());const itemIdx=lc.findIndex(c=>['item','item_vi','chỉ tiêu','name','item_name'].includes(c));const itemEnIdx=lc.findIndex(c=>['item_en','item english','english item'].includes(c));const periodIdx=reportPeriodIndexes(cols);
  if(itemIdx>=0&&periodIdx.length){const head=`<thead><tr><th>${escapeHtml(t('company.item'))}</th>${periodIdx.map(i=>`<th>${escapeHtml(cols[i])}</th>`).join('')}</tr></thead>`;const body=`<tbody>${(report.rows||[]).map(row=>{const label=STATE.lang==='en'?(row[itemEnIdx]||row[itemIdx]):(row[itemIdx]||row[itemEnIdx]);return `<tr><td>${escapeHtml(label??'')}</td>${periodIdx.map(i=>`<td>${typeof row[i]==='number'?fmt(row[i],2):escapeHtml(row[i]??'')}</td>`).join('')}</tr>`}).join('')}</tbody>`;table.innerHTML=head+body;return;}
  const safeIdx=periodIdx;const head=`<thead><tr>${safeIdx.map(i=>`<th>${escapeHtml(cols[i])}</th>`).join('')}</tr></thead>`;const body=`<tbody>${(report.rows||[]).map(row=>`<tr>${safeIdx.map(i=>`<td>${typeof row[i]==='number'?fmt(row[i],2):escapeHtml(row[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody>`;table.innerHTML=head+body;}

function compactIssue(text,type){const context=String(text||'').split(':')[0]||'';return `${type==='error'?t('data.error'):t('data.warning')}: ${context}. ${t('data.seeLogs')}`;}
function renderData(){const d=STATE.data;const global=STATE.resources?.global;const globalSource=(global?.feeds||[]).map(x=>x.source).filter(Boolean);const sections=[[t('data.market'),d.market,'market'],[t('data.macro'),d.macro,'macro'],[t('data.fundamental'),d.companies,'company'],[t('data.global'),{status:global?.status,source:globalSource},'global']];$('#sourceCards').innerHTML=sections.map(([name,s,key])=>`<article class="source-card"><span class="eyebrow">${escapeHtml(name)}</span><h3>${escapeHtml((s?.status||'unknown').toUpperCase())}</h3><p>${escapeHtml(sourceLabel(s?.source))}</p><div class="source-status">${t('data.asOf')}: ${escapeHtml(dateText(resourceObservationTime(key)))}</div><div class="source-status">${t('data.fetched')}: ${escapeHtml(dateText(resourceFetchedTime(key)))}</div></article>`).join('');const health=d.health||{};const items=[...(health.errors||[]).map(x=>['error',x]),...(health.warnings||[]).map(x=>['warning',x])];$('#healthList').innerHTML=items.length?items.map(([type,text])=>`<div class="health-item ${type}"><strong>${type==='error'?t('data.error').toUpperCase():t('data.warning').toUpperCase()}</strong><span>${escapeHtml(compactIssue(text,type))}</span></div>`).join(''):`<div class="health-item"><span>${t('data.noIssues')}</span></div>`;$('#methodList').innerHTML=METHOD_KEYS.map(k=>`<div class="formula-item"><strong>${escapeHtml(k)}</strong><span>${escapeHtml(t(`method.${k}`))}</span></div>`).join('');}

function renderAll(){translateStatic();renderStatus();renderOverview();renderMoney();renderMarket();renderCompany();renderData();}
const RESOURCE_PATHS={root:'data/rootvalue.json',market:'data/market.json',global:'data/global.json',companyDashboard:'data/company_dashboard.json',knowledge:'content/knowledge.json'};
async function fetchResource(path,signal){const res=await fetch(path,{cache:'no-store',signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json();}
function emptyRoot(error){return {pipeline_status:'error',generated_at:null,macro:{status:'error',metrics:[],missing_core:[]},market:{status:'error',rows:[],index:{}},companies:{status:'error',rows:{}},health:{errors:[`load:${error}`],warnings:[]}};}
async function loadData(){const loadId=++STATE.loadId;STATE.loadController?.abort();const controller=new AbortController();STATE.loadController=controller;const refresh=$('#refreshBtn');if(refresh){refresh.disabled=true;refresh.setAttribute('aria-busy','true');}const entries=Object.entries(RESOURCE_PATHS);const settled=await Promise.allSettled(entries.map(([,path])=>fetchResource(path,controller.signal)));if(loadId!==STATE.loadId)return;const next={...STATE.resources};const errors=[];settled.forEach((result,i)=>{const [key,path]=entries[i];if(result.status==='fulfilled')next[key]=result.value;else if(result.reason?.name!=='AbortError')errors.push(`${key}: ${path} (${result.reason?.message||'load failed'})`);});const root=next.root||STATE.resources.root||emptyRoot(errors[0]||'rootvalue snapshot unavailable');const data={...root};if(next.market)data.market=next.market;const baseHealth=root.health||{};data.health={...baseHealth,errors:[...(baseHealth.errors||[])],warnings:[...(baseHealth.warnings||[]),...errors.map(x=>`Resource refresh failed: ${x}`)]};STATE.resources=next;STATE.resourceErrors=errors;STATE.data=data;renderAll();window.dispatchEvent(new CustomEvent('rootvalue:data',{detail:{loadId,errors}}));if(refresh){refresh.disabled=false;refresh.removeAttribute('aria-busy');}}

translateStatic();wireControls();loadData();if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
