// Rootvalue V1.1 overlays: larger investigation list + observable SBV trajectory.
const enhancementStyle=document.createElement('style');enhancementStyle.textContent=`
.morning-brief{background:var(--surface);border:1px solid var(--line-strong);border-radius:10px;margin:0 0 18px}.brief-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;padding:16px 18px;border-bottom:1px solid var(--line)}.brief-head h2{font-size:20px;font-weight:600;letter-spacing:-.35px;margin:3px 0 0}.brief-asof{font-size:11px;color:var(--muted);white-space:nowrap}.brief-grid{display:grid;grid-template-columns:1fr 1.15fr 1fr}.brief-cell{padding:18px;min-height:220px}.brief-cell+.brief-cell{border-left:1px solid var(--line)}.brief-step{display:block;font-size:11px;font-weight:600;color:var(--muted);margin-bottom:18px}.brief-cell h3{font-size:22px;font-weight:600;letter-spacing:-.4px;margin:0 0 7px}.brief-cell>p{font-size:12px;line-height:1.55;color:var(--muted);margin:0}.brief-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:18px}.brief-fact{border-top:1px solid var(--line);padding-top:8px}.brief-fact span,.sector-row span{display:block;font-size:10px;color:var(--subtle)}.brief-fact strong{display:block;font-size:14px;font-weight:600;margin-top:3px}.sector-list{display:grid;margin-top:14px}.sector-row{display:grid;grid-template-columns:minmax(100px,1fr) auto auto;align-items:center;gap:12px;padding:8px 0;border-top:1px solid var(--line)}.sector-row b{font-size:12px;font-weight:600}.sector-row em{font-size:11px;font-style:normal;color:var(--muted)}.capital-posture{display:inline-flex;border-radius:4px;padding:4px 7px;font-size:10px;font-weight:600;background:var(--surface-2);color:var(--muted);margin-bottom:10px}.capital-posture.defensive{background:var(--danger-soft);color:var(--danger)}.capital-posture.prepare{background:var(--brand-soft);color:var(--brand)}.capital-list{margin:15px 0 0;padding:0;list-style:none;display:grid;gap:8px}.capital-list li{font-size:12px;line-height:1.45;padding-left:16px;position:relative}.capital-list li:before{content:'—';position:absolute;left:0;color:var(--subtle)}.brief-foot{border-top:1px solid var(--line);padding:10px 18px;font-size:10px;color:var(--subtle)}
.pick-grid{display:block;background:var(--surface);border:1px solid var(--line-strong);border-radius:10px;overflow:hidden}.pick-card{display:grid;grid-template-columns:minmax(170px,1.1fr) minmax(120px,.85fr) minmax(260px,1.6fr) minmax(145px,.8fr);gap:16px;align-items:center;padding:13px 15px;background:var(--surface);border:0;border-bottom:1px solid var(--line);min-height:0}.pick-card:last-child{border-bottom:0}.pick-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.pick-head>div{display:flex;align-items:baseline;gap:8px}.pick-head strong{font-size:18px;font-weight:600;letter-spacing:-.25px}.pick-index{font-size:10px;color:var(--subtle);font-weight:600}.pick-type{font-size:10px;font-weight:600;border-radius:4px;padding:4px 6px;background:var(--surface-2);color:var(--muted);white-space:nowrap}.pick-card.leader .pick-type{background:var(--brand-soft);color:var(--brand)}.pick-card.abnormal .pick-type{background:var(--warning-soft);color:var(--warning)}.pick-sector{font-size:12px;color:var(--muted)}.pick-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.pick-stats div{display:grid;gap:2px}.pick-stats span{font-size:10px;color:var(--subtle)}.pick-stats b{font-size:12px;font-weight:600}.pick-foot{display:flex;align-items:center;justify-content:space-between;gap:12px}.trajectory-panel{margin:0 0 12px}.trajectory-note{margin-top:6px!important}.trajectory-meta{display:grid;text-align:right;gap:1px;min-width:130px}.trajectory-meta strong{font-size:24px;font-weight:600}.trajectory-meta span,.trajectory-meta small{font-size:11px;color:var(--subtle)}.trajectory-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.trajectory-card{border:1px solid var(--line);background:var(--surface);border-radius:8px;padding:13px;min-height:118px}.trajectory-top{display:flex;align-items:center;justify-content:space-between;gap:8px}.trajectory-top>span{font-size:11px;color:var(--muted);font-weight:600}.trajectory-card>strong{display:block;font-size:19px;font-weight:600;margin:14px 0 4px;letter-spacing:-.2px}.trajectory-card>small{display:block;font-size:10px;color:var(--subtle);line-height:1.4}.trajectory-warning{margin-top:10px;padding-top:10px;border-top:1px solid var(--line);font-size:11px;line-height:1.5;color:var(--warning)}
.capital-discipline-panel{border-color:var(--line-strong);margin-bottom:16px}.capital-discipline-panel .capital-layout{display:grid;grid-template-columns:minmax(200px,.8fr) minmax(320px,1.2fr);gap:24px}.capital-discipline-panel h2{font-size:22px}.capital-disclaimer{margin-top:12px!important;font-size:10px!important;color:var(--subtle)!important}
.table-wrap.market-historical{background:var(--surface-2)}.table-wrap.market-historical tbody{opacity:.68}.table-wrap.market-historical .state-badge{filter:grayscale(.45)}
@media(max-width:1100px){.brief-grid{grid-template-columns:1fr}.brief-cell+.brief-cell{border-left:0;border-top:1px solid var(--line)}.brief-cell{min-height:0}.pick-card{grid-template-columns:1fr 1fr}.trajectory-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:650px){.brief-head{display:block}.brief-asof{display:block;margin-top:7px}.brief-cell{padding:15px}.brief-cell h3{font-size:19px}.pick-card{grid-template-columns:1fr;padding:14px}.pick-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.trajectory-grid{grid-template-columns:1fr}.trajectory-meta{text-align:left;margin-top:10px}.trajectory-panel .panel-head,.capital-discipline-panel .capital-layout{display:block}.capital-discipline-panel .capital-list{margin-top:18px}}
`;document.head.appendChild(enhancementStyle);

Object.assign(SECTORS,{
  'Securities':{vi:'Chứng khoán',en:'Securities'},
  'Real Estate':{vi:'Bất động sản',en:'Real Estate'},
  'Consumer & Retail':{vi:'Tiêu dùng & bán lẻ',en:'Consumer & Retail'},
  'Materials':{vi:'Vật liệu',en:'Materials'},
  'Energy':{vi:'Năng lượng',en:'Energy'}
});

Object.assign(I18N.vi,{
  'nav.money':'Tiền & thanh khoản','nav.money.short':'Thanh khoản','nav.market':'Thị trường','nav.market.short':'Thị trường',
  'overview.title':'Bản tin quyết định buổi sáng','overview.lead':'Diễn biến → leadership → kỷ luật vốn. Mỗi kết luận đều đi kèm dữ kiện và ngày nguồn.',
  'market.kicker':'BỀ RỘNG · LEADERSHIP','market.title':'Sức mạnh & mức tham gia','market.lead':'So sánh sức mạnh tương đối, độ rộng và mức tham gia. Giá và khối lượng không chứng minh tiền đang đi vào hay ra khỏi một mã.',
  'attention.kicker':'HÀNG ĐỢI QUYẾT ĐỊNH','attention.title':'Mã cần kiểm tra tiếp',
  'attention.note':'Tối đa 8 tín hiệu để điều tra; không phải khuyến nghị mua bán',
  'brief.title':'Diễn biến → Leadership → Kỷ luật vốn','brief.asOf':'Ngày nguồn thị trường','brief.change':'01 · Diễn biến','brief.leadership':'02 · Leadership','brief.capital':'03 · Kỷ luật vốn',
  'brief.breadth':'Độ rộng watchlist','brief.index20':'VNINDEX · 20 phiên','brief.leadingShare':'Dẫn dắt / cải thiện','brief.participation':'Mức tham gia TB','brief.sectorRs':'RS 20 phiên','brief.sectorBreadth':'mã tăng',
  'brief.changeWeak':'Độ rộng watchlist yếu','brief.changeStrong':'Độ rộng watchlist mở rộng','brief.changeMixed':'Watchlist phân hóa','brief.changeUnavailable':'Chưa đủ dữ liệu watchlist','brief.changeStale':'Snapshot watchlist đã quá hạn',
  'brief.noSector':'Chưa xác định được leadership ngành','brief.leadershipLocked':'Leadership hiện hành tạm khóa','brief.leadershipLockedText':'Không xếp hạng ngành từ snapshot thiếu hoặc quá hạn. Dữ liệu cũ chỉ còn giá trị tham chiếu lịch sử.','brief.disclaimer':'Độ rộng chỉ đo universe cấu hình, không đại diện toàn thị trường Việt Nam. Đây là khung phân bổ sự chú ý, không phải lệnh mua/bán; “mức tham gia” là biến đại diện từ khối lượng.',
  'capital.wait':'CHỜ DỮ LIỆU','capital.defensive':'GIẢM NHỊP ĐỘ','capital.observe':'QUAN SÁT CHỌN LỌC','capital.prepare':'CHUẨN BỊ CÓ ĐIỀU KIỆN',
  'capital.title.wait':'Chưa thay đổi trạng thái vốn','capital.title.defensive':'Không mở rộng rủi ro mới','capital.title.observe':'Giữ nhịp độ, theo dõi chọn lọc','capital.title.prepare':'Chuẩn bị danh sách; chỉ hành động khi xác nhận',
  'capital.panel':'Kỷ luật vốn hôm nay','capital.disclaimer':'Khung nghiên cứu chung; chưa sử dụng danh mục, mục tiêu tỷ trọng hoặc khẩu vị rủi ro cá nhân.',
  'capital.layersIncomplete':'Tín hiệu vốn hiện chỉ đọc market tape; lớp macro NHNN và BCTC 8 năm chưa đủ READY.','notice.marketOnly':'Snapshot thị trường dùng được, nhưng macro NHNN và BCTC 8 năm còn thiếu; kỷ luật vốn bên dưới chỉ dựa trên market tape.',
  'pick.leader':'Dẫn đầu sức mạnh ngành','pick.abnormal':'Đổi hạng bất thường','pick.other':'Theo dõi','pick.rank':'Hạng','pick.move':'Đổi hạng','pick.rs':'Sức mạnh 20P','pick.participation':'Mức tham gia',
  'sbv.trajectory.kicker':'DIỄN BIẾN NHNN','sbv.trajectory.title':'Dữ liệu quan sát theo thời gian','sbv.trajectory.note':'Mỗi lần chạy hệ thống lưu lại quan sát chính thức của NHNN. Đây là dữ liệu diễn biến, không phải nhận định.',
  'sbv.history':'Số quan sát','sbv.sourceObservation':'Ngày quan sát nguồn','sbv.current':'Hiện tại','sbv.change':'So với lần trước','sbv.noHistory':'Chưa đủ hai quan sát để tính thay đổi.',
  'metric.sbv_omo_awarded':'OMO trúng thầu','metric.sbv_omo_rate':'Lãi suất OMO','metric.sbv_m2_growth':'Tăng trưởng M2','metric.sbv_corp_deposit_growth':'Tiền gửi TCKT','metric.sbv_household_deposit_growth':'Tiền gửi dân cư',
  'sbv.backfillWarning':'Chuỗi quan sát chính thức đang được tích lũy từ Rootvalue; backfill 2018–nay vẫn chưa hoàn tất nên chưa dùng để gán xác suất phản ứng NHNN.',
  'market.coverage':'Độ phủ watchlist','market.picks':'Mã đang được theo dõi','market.noData':'Chưa có dữ liệu watchlist. Pipeline thị trường chưa chạy thành công.','market.picksLocked':'Hàng đợi quyết định tạm khóa vì snapshot watchlist thiếu hoặc quá hạn.','market.currentTable':'Bảng hiện hành cho universe cấu hình; không đại diện toàn thị trường Việt Nam.','market.historicalTable':'Bảng dưới đây chỉ là snapshot lịch sử ngày {date}; xếp hạng và trạng thái không được dùng cho quyết định hiện tại.',
  'missing.interbank_rate':'Lãi suất liên ngân hàng','missing.policy_rate':'Lãi suất điều hành','missing.omo':'Nghiệp vụ thị trường mở','missing.credit':'Tăng trưởng tín dụng','missing.money_supply':'Tổng phương tiện thanh toán','missing.cpi':'Lạm phát CPI','missing.exchange_rate':'Tỷ giá'
});
Object.assign(I18N.en,{
  'nav.money':'Liquidity & Capital','nav.money.short':'Liquidity','nav.market':'Market','nav.market.short':'Market',
  'overview.title':'Morning decision brief','overview.lead':'Change → leadership → capital discipline. Every conclusion carries evidence and a source date.',
  'market.kicker':'BREADTH · LEADERSHIP','market.title':'Strength & participation','market.lead':'Compare relative strength, breadth and participation. Price and volume do not prove that money is flowing into or out of a stock.',
  'attention.kicker':'DECISION QUEUE','attention.title':'Names to validate next',
  'attention.note':'Up to 8 investigation signals; not buy or sell recommendations',
  'brief.title':'Change → Leadership → Capital discipline','brief.asOf':'Market source date','brief.change':'01 · Change','brief.leadership':'02 · Leadership','brief.capital':'03 · Capital discipline',
  'brief.breadth':'Watchlist breadth','brief.index20':'VNINDEX · 20 sessions','brief.leadingShare':'Leading / improving','brief.participation':'Avg participation','brief.sectorRs':'20-session RS','brief.sectorBreadth':'advancing',
  'brief.changeWeak':'Watchlist breadth is weak','brief.changeStrong':'Watchlist breadth is expanding','brief.changeMixed':'The watchlist is selective','brief.changeUnavailable':'Watchlist data is not ready','brief.changeStale':'The watchlist snapshot is stale',
  'brief.noSector':'Sector leadership is not available','brief.leadershipLocked':'Current leadership is locked','brief.leadershipLockedText':'Sectors are not ranked from a missing or stale snapshot. Old data remains historical reference only.','brief.disclaimer':'Breadth covers the configured universe, not the entire Vietnam market. This is an attention framework, not a trade instruction; “participation” is a volume proxy.',
  'capital.wait':'WAIT FOR DATA','capital.defensive':'SLOW DOWN','capital.observe':'SELECTIVE WATCH','capital.prepare':'CONDITIONAL PREPARE',
  'capital.title.wait':'Do not change capital posture yet','capital.title.defensive':'Do not expand risk','capital.title.observe':'Keep pace and stay selective','capital.title.prepare':'Prepare a list; act only on confirmation',
  'capital.panel':'Capital discipline today','capital.disclaimer':'General research framework; no portfolio, target weights or personal risk tolerance is being used.',
  'capital.layersIncomplete':'Capital posture currently reads market tape only; the SBV macro and eight-year financial layers are not READY.','notice.marketOnly':'The market snapshot is usable, but SBV macro and eight-year financial layers are incomplete; the capital posture below is market-tape-only.',
  'pick.leader':'Sector RS leader','pick.abnormal':'Unusual rank mover','pick.other':'Watch','pick.rank':'Rank','pick.move':'Rank move','pick.rs':'20D strength','pick.participation':'Participation',
  'sbv.trajectory.kicker':'SBV TRAJECTORY','sbv.trajectory.title':'Observed data through time','sbv.trajectory.note':'Each pipeline run preserves official SBV observations. This is trajectory data, not an opinion.',
  'sbv.history':'Observations','sbv.sourceObservation':'Source observation date','sbv.current':'Current','sbv.change':'Vs prior observation','sbv.noHistory':'At least two observations are needed to calculate a change.',
  'metric.sbv_omo_awarded':'OMO awarded','metric.sbv_omo_rate':'OMO rate','metric.sbv_m2_growth':'M2 growth','metric.sbv_corp_deposit_growth':'Corporate deposits','metric.sbv_household_deposit_growth':'Household deposits',
  'sbv.backfillWarning':'The verified official series is accumulating from the date Rootvalue began collecting it; the 2018–present backfill is not complete, so SBV reaction probabilities remain disabled.',
  'market.coverage':'Watchlist coverage','market.picks':'Tracked names','market.noData':'No watchlist data yet. The dedicated market pipeline has not completed successfully.','market.picksLocked':'The decision queue is locked because the watchlist snapshot is missing or stale.','market.currentTable':'Current table for the configured universe; it does not represent the entire Vietnam market.','market.historicalTable':'The table below is a historical {date} snapshot; ranks and states must not drive current decisions.',
  'missing.interbank_rate':'Interbank rate','missing.policy_rate':'Policy rate','missing.omo':'Open-market operations','missing.credit':'Credit growth','missing.money_supply':'Money supply','missing.cpi':'CPI inflation','missing.exchange_rate':'Exchange rate'
});

function enhancedMetricLabel(key){return t(`metric.${key}`);}
function enhancedMetricUnit(unit){const raw=String(unit||'');if(STATE.lang==='vi')return raw;const map={'Tỷ đồng':'bn VND','tỷ':'bn VND','%/năm':'% p.a.','%':'%'};return map[raw]||raw;}
function fieldPoints(history,field){return (history||[]).map(x=>({value:toFinite(x?.[field]),date:x?.source_observation_date||x?.source_as_of||x?.source_date||null})).filter(x=>x.value!==null);}
function deltaNumber(a,b,d=2,suffix=''){if(a==null||b==null)return t('sbv.noHistory');const diff=b-a;return `${diff>0?'+':''}${fmt(diff,d)}${suffix}`;}
function enhancedMean(values=[]){const clean=values.map(toFinite).filter(v=>v!==null);return clean.length?clean.reduce((sum,v)=>sum+v,0)/clean.length:null;}
function vietnamCalendarDate(now=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return new Date(Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day)));}
function businessDaysSince(value,now=new Date()){const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);if(!match)return Infinity;const start=new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]))),end=vietnamCalendarDate(now);if(Number.isNaN(start.getTime()))return Infinity;if(start>=end)return 0;let days=0;for(let cursor=start.getTime()+86400000;cursor<=end.getTime();cursor+=86400000){const weekday=new Date(cursor).getUTCDay();if(weekday!==0&&weekday!==6)days++;}return days;}
function decisionSnapshot(d=STATE.data||{},now=new Date()){
  const market=d.market||{},rows=market.rows||[],returns=rows.map(r=>toFinite(r.return_1d)).filter(v=>v!==null),up=returns.filter(v=>v>0).length,breadth=returns.length?up/returns.length:null;
  const leaderCount=rows.filter(r=>['Leading','Improving'].includes(r.state)).length,leadingShare=rows.length?leaderCount/rows.length:null,participation=enhancedMean(rows.map(r=>r.volume_participation_5d_vs_20d));
  const grouped=new Map();rows.forEach(r=>{const key=r.sector||'—';if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r);});
  const sectors=[...grouped].map(([sector,members])=>{const sectorReturns=members.map(r=>toFinite(r.return_1d)).filter(v=>v!==null);return {sector,count:members.length,rs:enhancedMean(members.map(r=>r.rs_20d_vs_vnindex)),return1d:enhancedMean(sectorReturns),breadth:sectorReturns.length?sectorReturns.filter(v=>v>0).length/sectorReturns.length:null,participation:enhancedMean(members.map(r=>r.volume_participation_5d_vs_20d))};}).filter(s=>s.rs!==null).sort((a,b)=>b.rs-a.rs);
  const asOf=market.source_observation_date||market.as_of||'—',ageBusinessDays=businessDaysSince(asOf,now),selectionUsable=!String(market.selection_status||'').startsWith('blocked'),dataReady=['ok','stale'].includes(market.status)&&selectionUsable&&rows.length>0&&breadth!==null,stale=dataReady&&(market.status==='stale'||ageBusinessDays>1),ready=dataReady&&!stale,index1d=toFinite(market.index?.return_1d),index20d=toFinite(market.index?.return_20d);
  let tone='observe';if(!ready)tone='wait';else if(breadth<.35||(index1d!==null&&index1d<=-.01))tone='defensive';else if(breadth>=.55&&(index1d??-1)>0&&(leadingShare??0)>=.35)tone='prepare';
  return {ready,dataReady,stale,ageBusinessDays,rows,returns,up,breadth,leadingShare,participation,sectors,index1d,index20d,tone,asOf};
}
function capitalCopy(s){
  if(s.tone==='wait'){const reason=s.stale?(STATE.lang==='vi'?`Snapshot ngày ${s.asOf} đã chậm ${s.ageBusinessDays} ngày giao dịch; không phát sinh hướng dẫn vốn từ dữ liệu quá hạn.`:`The ${s.asOf} snapshot is ${s.ageBusinessDays} business days old; stale data does not produce capital guidance.`):(STATE.lang==='vi'?'Snapshot thị trường chưa đạt trạng thái sử dụng được; không suy diễn hành động từ dữ liệu thiếu.':'The market snapshot is not usable; no action is inferred from missing data.');return {reason,bullets:STATE.lang==='vi'?['Giữ nguyên trạng thái vốn.','Kiểm tra lại nguồn, ngày dữ liệu và độ phủ.','Đánh giá lại sau snapshot hợp lệ kế tiếp.']:['Keep the current capital posture.','Validate source, date and coverage.','Reassess after the next valid snapshot.']};}
  if(s.tone==='defensive'){const weakBreadth=s.breadth<.35,sharpIndexDrop=s.index1d!==null&&s.index1d<=-.01,reason=weakBreadth&&sharpIndexDrop?(STATE.lang==='vi'?`Chỉ ${s.up}/${s.returns.length} mã trong watchlist tăng (${fmt(s.breadth*100,0)}%) và VNINDEX giảm ${signedPct(s.index1d)}.`:`Only ${s.up}/${s.returns.length} watchlist names advanced (${fmt(s.breadth*100,0)}%) and VNINDEX fell ${signedPct(s.index1d)}.`):weakBreadth?(STATE.lang==='vi'?`Chỉ ${s.up}/${s.returns.length} mã trong watchlist tăng (${fmt(s.breadth*100,0)}%), dưới ngưỡng 35%.`:`Only ${s.up}/${s.returns.length} watchlist names advanced (${fmt(s.breadth*100,0)}%), below the 35% threshold.`):(STATE.lang==='vi'?`VNINDEX giảm ${signedPct(s.index1d)}, chạm/vượt ngưỡng cảnh báo -1%; độ rộng watchlist hiện ${fmt(s.breadth*100,0)}%.`:`VNINDEX fell ${signedPct(s.index1d)}, at or beyond the -1% warning threshold; watchlist breadth is ${fmt(s.breadth*100,0)}%.`);return {reason,bullets:STATE.lang==='vi'?['Ưu tiên thanh khoản và rà giới hạn rủi ro.','Không nâng rủi ro chỉ vì một mã tăng hạng.','Chờ độ rộng watchlist đạt ít nhất 55%, VNINDEX dương và leadership đồng thuận.']:['Prioritize liquidity and review risk limits.','Do not add risk from a single rank move.','Wait for watchlist breadth at or above 55%, a positive VNINDEX and aligned leadership.']};}
  if(s.tone==='prepare')return {reason:STATE.lang==='vi'?`Độ rộng watchlist ${fmt(s.breadth*100,0)}%, VNINDEX tăng và ${fmt(s.leadingShare*100,0)}% universe cấu hình đang dẫn dắt/cải thiện.`:`Watchlist breadth is ${fmt(s.breadth*100,0)}%, VNINDEX is positive and ${fmt(s.leadingShare*100,0)}% of the configured universe is leading or improving.`,bullets:STATE.lang==='vi'?['Xếp danh sách theo RS ngành, không theo cảm tính.','Yêu cầu giá và mức tham gia cùng xác nhận.','Đặt trước trigger và điều kiện phủ định.']:['Rank the list by sector RS, not intuition.','Require price and participation confirmation.','Define the trigger and invalidation first.']};
  return {reason:STATE.lang==='vi'?`Tín hiệu watchlist chưa đồng thuận: độ rộng ${fmt((s.breadth??0)*100,0)}%, leadership ${fmt((s.leadingShare??0)*100,0)}%.`:`Watchlist signals are not aligned: breadth ${fmt((s.breadth??0)*100,0)}%, leadership ${fmt((s.leadingShare??0)*100,0)}%.`,bullets:STATE.lang==='vi'?['Không đổi vị thế chỉ từ một phiên.','Theo dõi ngành RS dương và độ rộng cải thiện.','Chờ độ rộng và leadership đồng thuận.']:['Do not change posture from one session.','Watch sectors with positive RS and improving breadth.','Wait for breadth and leadership to align.']};
}
function renderMorningBrief(d){
  const s=decisionSnapshot(d),copy=capitalCopy(s),changeTitle=!s.dataReady?t('brief.changeUnavailable'):s.stale?t('brief.changeStale'):s.breadth<.35?t('brief.changeWeak'):s.breadth>=.55?t('brief.changeStrong'):t('brief.changeMixed');
  const changeText=!s.dataReady?(STATE.lang==='vi'?'Không có snapshot hợp lệ để kết luận.':'No valid snapshot is available.'):s.stale?(STATE.lang==='vi'?`Dữ liệu ngày ${s.asOf} đã chậm ${s.ageBusinessDays} ngày giao dịch; chỉ dùng để tham chiếu lịch sử.`:`The ${s.asOf} snapshot is ${s.ageBusinessDays} business days old and is shown for historical reference only.`):(STATE.lang==='vi'?`${s.up}/${s.returns.length} mã tăng; VNINDEX ${signedPct(s.index1d)} trong phiên.`:`${s.up}/${s.returns.length} names advanced; VNINDEX ${signedPct(s.index1d)} on the session.`);
  const top=s.ready?s.sectors[0]:null,leadTitle=!s.ready?t('brief.leadershipLocked'):top?(STATE.lang==='vi'?`${sectorLabel(top.sector)} dẫn theo RS 20 phiên`:`${sectorLabel(top.sector)} leads on 20-session RS`):t('brief.noSector'),leadText=!s.ready?t('brief.leadershipLockedText'):top?(STATE.lang==='vi'?`RS ${signedPct(top.rs)} so với VNINDEX; ${fmt((top.breadth??0)*100,0)}% mã trong ngành tăng phiên.`:`RS ${signedPct(top.rs)} versus VNINDEX; ${fmt((top.breadth??0)*100,0)}% of sector names advanced.`):'';
  const sectorRows=s.ready?s.sectors.slice(0,3).map(x=>`<div class="sector-row"><b>${escapeHtml(sectorLabel(x.sector))}</b><span class="${cls(x.rs)}">${signedPct(x.rs)}</span><em>${fmt((x.breadth??0)*100,0)}% ${escapeHtml(t('brief.sectorBreadth'))}</em></div>`).join(''):'';
  const postureClass=s.tone==='defensive'?'defensive':s.tone==='prepare'?'prepare':'',posture=t(`capital.${s.tone}`),capitalTitle=t(`capital.title.${s.tone}`);
  const root=$('#morningBrief');if(!root)return;root.innerHTML=`<div class="brief-head"><div><span class="eyebrow">MORNING BRIEF</span><h2>${escapeHtml(t('brief.title'))}</h2></div><span class="brief-asof">${escapeHtml(t('brief.asOf'))}: <strong>${escapeHtml(dateText(s.asOf))}</strong></span></div><div class="brief-grid"><article class="brief-cell"><span class="brief-step">${escapeHtml(t('brief.change'))}</span><h3>${escapeHtml(changeTitle)}</h3><p>${escapeHtml(changeText)}</p><div class="brief-facts"><div class="brief-fact"><span>${escapeHtml(t('brief.breadth'))}</span><strong>${s.breadth===null?'N/A':fmt(s.breadth*100,0)+'%'}</strong></div><div class="brief-fact"><span>${escapeHtml(t('brief.index20'))}</span><strong class="${cls(s.index20d)}">${signedPct(s.index20d)}</strong></div></div></article><article class="brief-cell"><span class="brief-step">${escapeHtml(t('brief.leadership'))}</span><h3>${escapeHtml(leadTitle)}</h3><p>${escapeHtml(leadText)}</p><div class="sector-list">${sectorRows}</div></article><article class="brief-cell"><span class="brief-step">${escapeHtml(t('brief.capital'))}</span><span class="capital-posture ${postureClass}">${escapeHtml(posture)}</span><h3>${escapeHtml(capitalTitle)}</h3><p>${escapeHtml(copy.reason)}</p><ul class="capital-list">${copy.bullets.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></article></div><div class="brief-foot">${escapeHtml(t('brief.disclaimer'))}</div>`;
}
function trajectoryCard(label,field,dataset,current,history,unit,decimals=2){const points=fieldPoints(history,field);const latestPoint=points.at(-1);const prior=points.length>=2?points.at(-2).value:null;const latest=latestPoint?.value??toFinite(current?.[field]);const sourceDate=latestPoint?.date||current?.source_observation_dates?.[dataset]||current?.datasets?.[dataset]?.source_observation_date||'—';const series=points.map(x=>x.value);const localizedUnit=enhancedMetricUnit(unit);const deltaUnit=unit==='%'?'pp':localizedUnit?` ${localizedUnit}`:'';return `<article class="trajectory-card"><div class="trajectory-top"><span>${escapeHtml(label)}</span>${sparkline(series)}</div><strong>${latest==null?'N/A':`${fmt(latest,decimals)}${localizedUnit?' '+escapeHtml(localizedUnit):''}`}</strong><small>${escapeHtml(t('sbv.sourceObservation'))}: ${escapeHtml(sourceDate)}<br>${escapeHtml(prior==null?t('sbv.noHistory'):deltaNumber(prior,latest,decimals,deltaUnit))}</small></article>`;}

renderOverview=function(){const d=STATE.data;const root=$('#overviewNotice');if(d.pipeline_status==='not_run')root.innerHTML=notice(t('notice.notRun'),'warning');else if(d.health?.errors?.length)root.innerHTML=notice(`${t('notice.errors')} (${d.health.errors.length})`,'error');else if(d.pipeline_status==='partial'&&d.market?.status==='ok')root.innerHTML=notice(t('notice.marketOnly'),'warning');else if(d.pipeline_status==='partial')root.innerHTML=notice(t('notice.partial'),'warning');else root.innerHTML='';renderMorningBrief(d);
  const idx=d.market?.index||{},usd=metricByKey('usd_vcb_sell'),gold=metricByKey('gold_sjc_sell'),rows=d.market?.rows||[],snapshot=decisionSnapshot(d),leading=snapshot.ready?[...rows].filter(r=>toFinite(r.rank_current)!==null).sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current))[0]:null;
  $('#systemMetrics').innerHTML=[
    metricCard(t('metric.vnindex'),fmt(idx.close,2),`1D ${signedPct(idx.return_1d)} · 20D ${signedPct(idx.return_20d)}`,d.market?.source||''),
    metricCard(t('metric.fx'),usd?fmt(usd.value,0):'N/A',t('metric.fxDesc'),usd?.source||''),
    metricCard(t('metric.gold'),gold?fmt(gold.value,0):'N/A',t('metric.goldDesc'),gold?.source||''),
    metricCard(t('brief.breadth'),snapshot.breadth===null?'N/A':`${fmt(snapshot.breadth*100,0)}%`,leading?`${t('metric.leader')}: ${leading.symbol} · ${signedPct(leading.rs_20d_vs_vnindex)}`:'N/A',`${t('market.coverage')}: ${rows.length}`)
  ].join('');
  const picks=(d.market?.picks||[]).slice(0,8);const list=snapshot.ready?picks:[];
  const box=$('#changeList');box.className='pick-grid';box.innerHTML=list.length?list.map((r,i)=>{const type=r.selection_type||((i<3)?'RelativeStrengthLeader':'AbnormalMovement');const isLeader=['RelativeStrengthLeader','Leader'].includes(type);const isAbnormal=['AbnormalMovement','Abnormal'].includes(type);const typeLabel=isLeader?t('pick.leader'):isAbnormal?t('pick.abnormal'):t('pick.other');const participation=toFinite(r.volume_participation_5d_vs_20d);return `<article class="pick-card ${isLeader?'leader':isAbnormal?'abnormal':''}"><div class="pick-head"><div><span class="pick-index">${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(r.symbol)}</strong></div><span class="pick-type">${escapeHtml(typeLabel)}</span></div><div class="pick-sector">${escapeHtml(sectorLabel(r.sector))}</div><div class="pick-stats"><div><span>${t('pick.rank')}</span><b>#${rankText(r.rank_current)}</b></div><div><span>${t('pick.move')}</span><b class="${cls(r.rank_delta)}">${signed(r.rank_delta,0)}</b></div><div><span>${t('pick.rs')}</span><b class="${cls(r.rs_20d_vs_vnindex)}">${signedPct(r.rs_20d_vs_vnindex)}</b></div><div><span>${t('pick.participation')}</span><b>${participation===null?'N/A':`${fmt(participation,2)}x`}</b></div></div><div class="pick-foot"><span class="state-badge ${escapeHtml(r.state)}">${escapeHtml(stateLabel(r.state))}</span>${sparkline(r.sparkline)}</div></article>`}).join(''):notice(snapshot.ready?t('market.noData'):t('market.picksLocked'),'warning');};

renderMoney=function(){const d=STATE.data;const usd=metricByKey('usd_vcb_sell');const rows=d.market?.rows||[];const leader=decisionSnapshot(d).ready?[...rows].filter(r=>toFinite(r.rank_current)!==null).sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current))[0]:null;$('#externalValue').textContent=t('money.externalMissing');$('#fxValue').textContent=toFinite(usd?.value)!==null?`${fmt(usd.value,0)} VND/USD`:t('money.fxMissing');const missing=d.macro?.missing_core||[];const omo=toFinite(d.macro?.sbv_current?.omo_awarded_bn_vnd);$('#liquidityValue').textContent=omo!==null?`${fmt(omo,0)} tỷ OMO`:t('money.liquidityMissing');$('#allocationValue').textContent=leader?`${t('money.rsLeader')}: ${leader.symbol}`:t('money.allocationMissing');const ready=d.macro?.reaction_engine_status==='data_ready';$('#reactionStatus').textContent=ready?t('reaction.ready'):t('reaction.missing');$('#reactionStatus').className=`pill ${ready?'ok':'warning'}`;$('#missingCore').innerHTML=missing.length?missing.map(x=>`<div class="missing-item"><strong>${escapeHtml(missingLabel(x))}</strong><span>${t('missing.status')}</span></div>`).join(''):`<div class="missing-item"><strong>${t('missing.coreSet')}</strong><span>${t('missing.available')}</span></div>`;
  const metrics=d.macro?.metrics||[];$('#macroMetrics').innerHTML=metrics.length?metrics.map(m=>`<div class="stack-item"><div><strong>${escapeHtml(enhancedMetricLabel(m.key)||m.key)}</strong><small class="metric-source-inline">${escapeHtml(sourceLabel(m.source||''))}</small></div><div>${fmt(m.value,2)} <small class="metric-unit">${escapeHtml(enhancedMetricUnit(m.unit))}</small></div></div>`).join(''):`<div class="stack-item"><span>${t('proxy.none')}</span><small>N/A</small></div>`;
  const screen=$('[data-screen="money"]'),snapshot=decisionSnapshot(d),copy=capitalCopy(snapshot),postureClass=snapshot.tone==='defensive'?'defensive':snapshot.tone==='prepare'?'prepare':'',layerDisclaimer=d.pipeline_status==='partial'?t('capital.layersIncomplete'):t('capital.disclaimer');let capital=$('#capitalDisciplinePanel');if(!capital){capital=document.createElement('article');capital.className='panel capital-discipline-panel';capital.id='capitalDisciplinePanel';$('.flow-map',screen)?.before(capital);}capital.innerHTML=`<div class="capital-layout"><div><span class="eyebrow">${escapeHtml(t('brief.capital'))}</span><span class="capital-posture ${postureClass}">${escapeHtml(t(`capital.${snapshot.tone}`))}</span><h2>${escapeHtml(t('capital.panel'))}: ${escapeHtml(t(`capital.title.${snapshot.tone}`))}</h2><p>${escapeHtml(copy.reason)}</p><p class="capital-disclaimer">${escapeHtml(layerDisclaimer)}</p></div><ul class="capital-list">${copy.bullets.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>`;let panel=$('#sbvTrajectoryPanel');if(!panel){panel=document.createElement('article');panel.className='panel trajectory-panel';panel.id='sbvTrajectoryPanel';const anchor=$('.two-col',screen);anchor?.before(panel);}const hist=d.macro?.sbv_history?.observations||[];const cur=d.macro?.sbv_current||{};panel.innerHTML=`<div class="panel-head"><div><span class="eyebrow">${t('sbv.trajectory.kicker')}</span><h2>${t('sbv.trajectory.title')}</h2><p class="trajectory-note">${t('sbv.trajectory.note')}</p></div><div class="trajectory-meta"><strong>${hist.length}</strong><span>${t('sbv.history')}</span></div></div><div class="trajectory-grid" id="sbvTrajectoryGrid">${trajectoryCard(t('metric.sbv_omo_awarded'),'omo_awarded_bn_vnd','omo_latest',cur,hist,'tỷ',0)}${trajectoryCard(t('metric.sbv_omo_rate'),'omo_rate_pct','omo_latest',cur,hist,'%',2)}${trajectoryCard(t('metric.sbv_m2_growth'),'m2_growth_ytd_pct','money_supply_deposits',cur,hist,'%',2)}${trajectoryCard(t('metric.sbv_corp_deposit_growth'),'corp_deposit_growth_ytd_pct','money_supply_deposits',cur,hist,'%',2)}${trajectoryCard(t('metric.sbv_household_deposit_growth'),'household_deposit_growth_ytd_pct','money_supply_deposits',cur,hist,'%',2)}</div><div class="trajectory-warning">${escapeHtml(t('sbv.backfillWarning'))}</div>`;};

renderMarket=function(){const d=STATE.data,snapshot=decisionSnapshot(d),rows=[...(d.market?.rows||[])].sort((a,b)=>rankValue(a.rank_current)-rankValue(b.rank_current)),screen=$('[data-screen="market"]');let marketNotice=$('#marketNotice');if(!marketNotice){marketNotice=document.createElement('div');marketNotice.id='marketNotice';marketNotice.setAttribute('aria-live','polite');$('.screen-head',screen)?.after(marketNotice);}const tableWrap=$('.table-wrap',screen);tableWrap?.classList.toggle('market-historical',!snapshot.ready&&rows.length>0);const table=$('.data-table',screen);table?.setAttribute('aria-describedby','marketNotice');const noticeText=snapshot.ready?`${t('market.currentTable')} ${t('brief.asOf')}: ${dateText(snapshot.asOf)}.`:rows.length?t('market.historicalTable').replace('{date}',dateText(snapshot.asOf)):t('market.noData');marketNotice.innerHTML=notice(noticeText,snapshot.ready?'':'warning');$('#marketBody').innerHTML=rows.length?rows.map(r=>{const participation=toFinite(r.volume_participation_5d_vs_20d);return `<tr><td><span class="ticker">${escapeHtml(r.symbol)}</span></td><td>${escapeHtml(sectorLabel(r.sector))}</td><td>${fmt(r.close,2)}</td><td class="${cls(r.return_1d)}">${signedPct(r.return_1d)}</td><td class="${cls(r.rs_20d_vs_vnindex)}">${signedPct(r.rs_20d_vs_vnindex)}</td><td>#${rankText(r.rank_current)}</td><td class="${cls(r.rank_delta)}">${signed(r.rank_delta,0)}</td><td>${participation===null?'N/A':`${fmt(participation,2)}x`}</td><td>${pct(r.range_position_20d,0)}</td><td><span class="state-badge ${escapeHtml(r.state)}">${escapeHtml(stateLabel(r.state))}</span></td><td>${sparkline(r.sparkline)}</td></tr>`}).join(''):`<tr><td colspan="11">${escapeHtml(t('market.noData'))}</td></tr>`;$('#marketMethod').innerHTML=`<strong>${t('market.coverage')}: ${rows.length}</strong> · `+METHOD_KEYS.map(k=>`<strong>${escapeHtml(k)}</strong>: ${escapeHtml(t(`method.${k}`))}`).join(' · ');};

// If the base app finished loading before this overlay arrived, rerender with the enhanced views.
if(STATE.data)renderAll();
